### PR TITLE
add: added serverless config

### PR DESCRIPTION
**Pull request by fetchMachine**
Manual Configured Links:

- S3 http://rs-app-test.s3-website-eu-west-1.amazonaws.com
- cloudfront https://d1ejsrf9l79d08.cloudfront.net

Servreless Configured Links

- S3 http://rss-shop-serverless-bucket.s3-website-eu-west-1.amazonaws.com
- cloudfront https://dzfkk71q2g2nw.cloudfront.net

### CODE REVIEW

**Comment by prostoslw** [comment]
Could you please explain which minor changes did you do?
https://github.com/EPAM-JS-Competency-center/cloud-development-course-initial/blob/main/task2-serve-spa-in-s3-cloudfront/task.md
image

**Comment by prostoslw** [comment]
Could you please explain which minor changes did you do?
https://github.com/EPAM-JS-Competency-center/cloud-development-course-initial/blob/main/task2-serve-spa-in-s3-cloudfront/task.md
image

**Comment by fetchMachine** [comment]
@prostoslw there are no any requirements to change app in the EVALUATION CRITERIA. And we must check the EVALUATION CRITERIA, not the intermediate steps.

**Comment by fetchMachine** [comment]
> Could you please explain which minor changes did you do?
> https://github.com/EPAM-JS-Competency-center/cloud-development-course-initial/blob/main/task2-serve-spa-in-s3-cloudfront/task.md
> image

**Comment by prostoslw** [comment]
> @prostoslw there are no any requirements to change app in the EVALUATION CRITERIA. And we must check the EVALUATION CRITERIA, not the intermediate steps.

Is it so hard to complete all steps for you? Ok

**Comment by prostoslw** [comment]
> @prostoslw there are no any requirements to change app in the EVALUATION CRITERIA. And we must check the EVALUATION CRITERIA, not the intermediate steps.

Could you please complete 4 step?

**Pull request merged**
